/**
 * Check the pages the static build emits, for the things a link check
 * cannot see: what the 404 page says, the sitemap's namespace, and whether
 * the sidebar's own rules survive the cascade.
 *
 *   bun run scripts/check-output.ts
 */
import {readdirSync, readFileSync, statSync, existsSync} from "node:fs";
import {join, resolve} from "node:path";

const PUBLIC = resolve(import.meta.dirname, "../dist/public");

if (!existsSync(PUBLIC)) {
	console.error(`No build to check at ${PUBLIC}. Run: bun run static`);
	process.exit(1);
}

let failures = 0;

function report(ok: boolean, name: string, detail = ""): void {
	console.log(`${ok ? "ok  " : "FAIL"} ${name}${detail ? " — " + detail : ""}`);
	if (!ok) failures++;
}

function walk(dir: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir)) {
		const path = join(dir, entry);
		if (statSync(path).isDirectory()) {
			out.push(...walk(path));
		} else if (path.endsWith(".html")) {
			out.push(path);
		}
	}
	return out;
}

/**
 * The page GitHub Pages serves for every missing URL is written once, so it
 * cannot name the path the visitor asked for. It used to be generated by
 * fetching an invented path, and said so.
 */
const notFound = readFileSync(join(PUBLIC, "404.html"), "utf8");
const ogURL = notFound.match(/property="og:url" content="([^"]*)"/)?.[1] ?? "";
report(
	!/There is no page at/.test(notFound),
	"404 page names no path",
	ogURL && new URL(ogURL).pathname !== "/404.html"
		? `body text; og:url is ${ogURL}`
		: "",
);
report(
	new URL(ogURL || "https://example.com/none/").pathname === "/404.html",
	"404 page's og:url is its own path",
	ogURL,
);

const sitemap = readFileSync(join(PUBLIC, "sitemap.xml"), "utf8");
report(
	sitemap.includes('xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"'),
	"sitemap uses the sitemaps.org namespace",
	sitemap.match(/xmlns="([^"]*)"/)?.[1] ?? "no xmlns",
);

/**
 * The sidebar is fixed over scrolling content, so whichever rule wins has to
 * paint a background color. A bare `background:` shorthand resets the color
 * to transparent, which is how a `background-color` written above it was
 * lost.
 */
const sidebarPages = walk(PUBLIC).filter((file) =>
	readFileSync(file, "utf8").includes('id="sidebar"'),
);
report(sidebarPages.length > 0, "a built page has a sidebar");

for (const file of sidebarPages.slice(0, 1)) {
	const html = readFileSync(file, "utf8");
	const className = html.match(/id="sidebar" class="([^"]+)"/)?.[1] ?? "";
	const blocks = Array.from(
		html.matchAll(new RegExp(`\\.${className}\\{([^}]*)\\}`, "g")),
	).map((match) => match[1]);
	const painted = blocks.filter((block) => /background:/.test(block));
	report(painted.length > 0, "the sidebar sets a background");
	for (const block of painted) {
		report(
			/background:[^;]*var\(--bg-color\)/.test(block),
			"the sidebar's background carries its color",
			block.match(/background:[^;]*/)?.[0] ?? "",
		);
	}
}

if (failures > 0) {
	console.error(`\n${failures} check(s) failed.`);
	process.exit(1);
}

console.log("\nBuilt output checks passed.");
