import {jsx} from "@b9g/crank/standalone";
import {css} from "@emotion/css";
import {Marked} from "@b9g/crankdown";

import {Root} from "../components/root.js";
import {components} from "../components/marked-components.js";

/**
 * SUPPORT.md, rendered.
 *
 * The file is generated by probing the engine, so this page is a build-time
 * snapshot of what the library measurably does rather than a claim anybody
 * maintains by hand. Its own leading "# Support" heading is dropped, since
 * the page supplies one.
 */
export default async function Support({url}: {url: string}) {
	const repoDir = await self.directories.open("repo");
	const fileHandle = await repoDir.getFileHandle("SUPPORT.md");
	const file = await fileHandle.getFile();
	const markdown = (await file.text()).replace(/^# Support\n+/, "");

	return jsx`
		<${Root}
			title="TermDOM | Support"
			url=${url}
			description="Every CSS feature TermDOM supports, measured by probing the engine rather than asserted by hand."
		>
			<main data-pagefind-body class=${css`
				max-width: 900px;
				margin: 0 auto;
				padding: 5rem 1.2rem 2rem;
			`}>
				<h1>Support</h1>
				<${Marked} markdown=${markdown} components=${components} />
			</main>
		<//Root>
	`;
}
