import {jsx} from "@b9g/crank/standalone";
import {css} from "@emotion/css";
import {Marked} from "@b9g/crankdown";

import {Root} from "../components/root.js";
import {components} from "../components/marked-components.js";

/**
 * COMPATIBILITY.md, rendered. Generated by the probe suite
 * (`bun run support`); its own heading is dropped, the page supplies one.
 */
export default async function Support({url}: {url: string}) {
	const repoDir = await self.directories.open("repo");
	const fileHandle = await repoDir.getFileHandle("COMPATIBILITY.md");
	const file = await fileHandle.getFile();
	// COMPATIBILITY.md leads with a generated-by comment; strip its own
	// heading wherever it sits, since the page supplies one.
	const markdown = (await file.text()).replace(/^# Compatibility\n+/m, "");

	return jsx`
		<${Root}
			title="TermDOM | Compatibility"
			url=${url}
			description="The DOM APIs, selectors, and CSS TermDOM supports, generated by a probe suite against the engine."
		>
			<main data-pagefind-body class=${css`
				max-width: 900px;
				margin: 0 auto;
				padding: 5rem 1.2rem 2rem;
			`}>
				<h1>Compatibility</h1>
				<${Marked} markdown=${markdown} components=${components} />
			</main>
		<//Root>
	`;
}
